server:
  port: ${PORT:8081}

app:
  token:
    secret-key: ${JWT_SECRET_KEY:bWluaGFzZWNyZXRyYW5kb20=}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


